#define Pi 3.141592654

#define MMP_WINDOW_LABEL "Maths - Mini Project"
#define MMP_AUTHORS "Axel LE BOT | Andrew LENC"

#define MMP_LAYER_INDEX_LANDMARK_SEGMENT 1
#define MMP_LAYER_INDEX_LANDMARK_POINTS 2
#define MMP_LAYER_INDEX_DRAW_SEGMENT 3
#define MMP_LAYER_INDEX_DRAW_POINT 4